/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_FTGlyph */

#ifndef _Included_generaloss_freetype_FTGlyph
#define _Included_generaloss_freetype_FTGlyph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_FTGlyph
 * Method:    strokeBorder
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FTGlyph_strokeBorder
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     generaloss_freetype_FTGlyph
 * Method:    toBitmap
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FTGlyph_toBitmap
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_FTGlyph
 * Method:    getBitmap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FTGlyph_getBitmap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FTGlyph
 * Method:    getLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FTGlyph_getLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FTGlyph
 * Method:    getTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FTGlyph_getTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FTGlyph
 * Method:    done
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FTGlyph_done
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
