/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_FTSizeMetrics */

#ifndef _Included_generaloss_freetype_FTSizeMetrics
#define _Included_generaloss_freetype_FTSizeMetrics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_FTSizeMetrics
 * Method:    getXppem
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FTSizeMetrics_getXppem
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FTSizeMetrics
 * Method:    getYppem
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FTSizeMetrics_getYppem
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FTSizeMetrics
 * Method:    getXscale
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FTSizeMetrics_getXscale
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FTSizeMetrics
 * Method:    getYscale
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FTSizeMetrics_getYscale
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FTSizeMetrics
 * Method:    getAscender
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FTSizeMetrics_getAscender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FTSizeMetrics
 * Method:    getDescender
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FTSizeMetrics_getDescender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FTSizeMetrics
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FTSizeMetrics_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FTSizeMetrics
 * Method:    getMaxAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FTSizeMetrics_getMaxAdvance
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
